#!/usr/bin/env bash
# test-verify.sh -- unit tests for scripts/lib/verify.sh
# Validates verification gate and debugger fix logic with mock Claude invocations.
#
# Usage:
#   ./tests/test-verify.sh

set -euo pipefail

PASS=0
FAIL=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TMP_DIR=""

cleanup() {
    if [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]]; then
        rm -rf "$TMP_DIR"
    fi
}
trap cleanup EXIT

TMP_DIR="$(mktemp -d)"

# ── helpers ──────────────────────────────────────────────────

pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }

assert_eq() {
    local actual="$1" expected="$2" label="$3"
    if [[ "$actual" == "$expected" ]]; then
        pass "$label"
    else
        fail "$label -- expected '$expected', got '$actual'"
    fi
}

assert_contains() {
    local haystack="$1" needle="$2" label="$3"
    if echo "$haystack" | grep -qF "$needle"; then
        pass "$label"
    else
        fail "$label -- '$needle' not found in output"
    fi
}

assert_not_contains() {
    local haystack="$1" needle="$2" label="$3"
    if echo "$haystack" | grep -qF "$needle"; then
        fail "$label -- '$needle' unexpectedly found in output"
    else
        pass "$label"
    fi
}

# ── source the library under test ────────────────────────────

source "$REPO_ROOT/scripts/lib/verify.sh"

# ── create mock claude scripts ───────────────────────────────

MOCK_BIN="$TMP_DIR/mock-bin"
mkdir -p "$MOCK_BIN"

# mock claude that outputs GATE_PASS
create_mock_claude_pass() {
    cat > "$MOCK_BIN/claude" <<'MOCKEOF'
#!/usr/bin/env bash
echo "GATE_PASS"
exit 0
MOCKEOF
    chmod +x "$MOCK_BIN/claude"
}

# mock claude that outputs GATE_FAIL with gap description
create_mock_claude_fail() {
    cat > "$MOCK_BIN/claude" <<'MOCKEOF'
#!/usr/bin/env bash
echo "GATE_FAIL"
echo "Missing registration: commands/new-cmd.md not added to plugin.json"
exit 0
MOCKEOF
    chmod +x "$MOCK_BIN/claude"
}

# mock claude for debugger that outputs FIX_APPLIED
create_mock_claude_fix_applied() {
    cat > "$MOCK_BIN/claude" <<'MOCKEOF'
#!/usr/bin/env bash
echo "FIX_APPLIED"
exit 0
MOCKEOF
    chmod +x "$MOCK_BIN/claude"
}

# mock claude for debugger that does NOT output FIX_APPLIED (failure)
create_mock_claude_fix_failed() {
    cat > "$MOCK_BIN/claude" <<'MOCKEOF'
#!/usr/bin/env bash
echo "Unable to determine fix."
exit 0
MOCKEOF
    chmod +x "$MOCK_BIN/claude"
}

# ── create a minimal git repo for diff tests ─────────────────

setup_git_repo() {
    local repo_dir
    repo_dir=$(mktemp -d "$TMP_DIR/repo-XXXXXX")
    git -C "$repo_dir" init -q 2>/dev/null
    git -C "$repo_dir" config user.email "test@test.com" 2>/dev/null
    git -C "$repo_dir" config user.name "Test" 2>/dev/null

    # initial commit with a file
    echo "initial" > "$repo_dir/existing.txt"
    git -C "$repo_dir" add existing.txt 2>/dev/null
    git -C "$repo_dir" commit -q -m "initial commit" 2>/dev/null

    printf '%s' "$repo_dir"
}

# ── create a minimal project profile ─────────────────────────

create_profile() {
    local specs_dir="$1"
    mkdir -p "$specs_dir"
    cat > "$specs_dir/_project-profile.md" <<'PROFILE'
> Auto-generated by spec-scanner. Last updated: 2026-04-01

## Stack
- Framework: Custom Plugin
- Language: Bash/Markdown

## Patterns
### Slash Commands [confidence: high]
Commands are defined as `.md` files in `commands/`.

## Entity Registry
| Entity | Create | Read | Update | Delete | Notes |
|--------|--------|------|--------|--------|-------|
| (none) | — | — | — | — | — |

## Registration Points
- `.claude-plugin/plugin.json:agents` — Register new agents here
- `.claude-plugin/plugin.json:commands` — Register new commands here

## Regression Markers
(none)

## Manual Overrides
(user-editable -- preserved across rescans)
PROFILE
}

# ══════════════════════════════════════════════════════════════
echo "=== Test 1: run_verification_gate -- no profile exists ==="
# ══════════════════════════════════════════════════════════════

test1_spec_dir="$TMP_DIR/no-profile/specs/my-feature"
mkdir -p "$test1_spec_dir"
# no _project-profile.md in the parent specs dir

output=$(run_verification_gate "$test1_spec_dir" "T-1" "/tmp" 2>&1)
exit_code=$?

assert_eq "$exit_code" "0" "no-profile gate exits 0"
assert_contains "$output" "No project profile -- verification gate skipped." "no-profile prints skip message"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 2: run_verification_gate -- profile exists, new file IS registered ==="
# ══════════════════════════════════════════════════════════════

# set up a git repo with a diff showing a new file + registration file modified
test2_repo=$(setup_git_repo)
test2_specs="$TMP_DIR/test2-specs"
create_profile "$test2_specs"
test2_spec_dir="$test2_specs/my-feature"
mkdir -p "$test2_spec_dir"

# add new files and modify registration file in the repo
echo "new agent" > "$test2_repo/new-agent.md"
echo '{"agents": [{"name": "new-agent"}]}' > "$test2_repo/plugin.json"
git -C "$test2_repo" add new-agent.md plugin.json
git -C "$test2_repo" commit -q -m "add new agent and register it"

# mock claude to return GATE_PASS
create_mock_claude_pass

output=$(PATH="$MOCK_BIN:$PATH" run_verification_gate "$test2_spec_dir" "T-1" "$test2_repo" 2>&1)
exit_code=$?

assert_eq "$exit_code" "0" "registered artifact gate exits 0"
assert_not_contains "$output" "GATE_FAIL" "no GATE_FAIL when artifact is registered"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 3: run_verification_gate -- profile exists, new file NOT registered ==="
# ══════════════════════════════════════════════════════════════

test3_repo=$(setup_git_repo)
test3_specs="$TMP_DIR/test3-specs"
create_profile "$test3_specs"
test3_spec_dir="$test3_specs/my-feature"
mkdir -p "$test3_spec_dir"

# add new file but do NOT modify registration file
echo "new command" > "$test3_repo/new-cmd.md"
git -C "$test3_repo" add new-cmd.md
git -C "$test3_repo" commit -q -m "add new command without registering"

# mock claude to return GATE_FAIL
create_mock_claude_fail

exit_code=0
output=$(PATH="$MOCK_BIN:$PATH" run_verification_gate "$test3_spec_dir" "T-2" "$test3_repo" 2>&1) || exit_code=$?

assert_eq "$exit_code" "1" "unregistered artifact gate exits 1"
assert_contains "$output" "Missing registration" "gap description mentions missing registration"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 4: run_verification_gate -- no registration points in profile ==="
# ══════════════════════════════════════════════════════════════

test4_specs="$TMP_DIR/test4-specs"
mkdir -p "$test4_specs"
# profile without a Registration Points section at all
cat > "$test4_specs/_project-profile.md" <<'PROFILE'
## Stack
- Language: Bash

## Patterns
(none)

## Entity Registry
(none)

## Regression Markers
(none)

## Manual Overrides
(user-editable)
PROFILE

test4_spec_dir="$test4_specs/my-feature"
mkdir -p "$test4_spec_dir"

output=$(run_verification_gate "$test4_spec_dir" "T-1" "/tmp" 2>&1)
exit_code=$?

assert_eq "$exit_code" "0" "missing registration section exits 0"
assert_contains "$output" "No registration points in profile -- verification gate skipped." "prints skip message when no registration section"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 5: run_debugger_fix -- successful fix ==="
# ══════════════════════════════════════════════════════════════

test5_repo=$(setup_git_repo)

create_mock_claude_fix_applied

output=$(PATH="$MOCK_BIN:$PATH" run_debugger_fix "/tmp/specs/feature" "T-3" "Missing: new-cmd.md not in plugin.json" "$test5_repo" 2>&1)
exit_code=$?

assert_eq "$exit_code" "0" "debugger fix exits 0 on FIX_APPLIED"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 6: run_debugger_fix -- failed fix ==="
# ══════════════════════════════════════════════════════════════

test6_repo=$(setup_git_repo)

create_mock_claude_fix_failed

exit_code=0
output=$(PATH="$MOCK_BIN:$PATH" run_debugger_fix "/tmp/specs/feature" "T-4" "Missing: new-route not in router" "$test6_repo" 2>&1) || exit_code=$?

assert_eq "$exit_code" "1" "debugger fix exits 1 when fix not applied"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 7: run_debugger_fix -- prompt contains gap description ==="
# ══════════════════════════════════════════════════════════════

# mock claude that echoes its stdin/args so we can verify the prompt
cat > "$MOCK_BIN/claude" <<'MOCKEOF'
#!/usr/bin/env bash
# capture the prompt argument for inspection
for arg in "$@"; do
    if [[ "$prev" == "-p" ]]; then
        echo "$arg" > /tmp/test-verify-prompt-capture.txt
        break
    fi
    prev="$arg"
done
echo "FIX_APPLIED"
exit 0
MOCKEOF
chmod +x "$MOCK_BIN/claude"

test7_repo=$(setup_git_repo)
gap="commands/foo.md not registered in plugin.json"

PATH="$MOCK_BIN:$PATH" run_debugger_fix "/tmp/specs/feature" "T-5" "$gap" "$test7_repo" 2>&1
captured_prompt=$(cat /tmp/test-verify-prompt-capture.txt 2>/dev/null || echo "")
rm -f /tmp/test-verify-prompt-capture.txt

assert_contains "$captured_prompt" "$gap" "debugger prompt contains gap description"
assert_contains "$captured_prompt" "T-5" "debugger prompt contains task ID"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Test 8: run_verification_gate -- no diff detected ==="
# ══════════════════════════════════════════════════════════════

test8_specs="$TMP_DIR/test8-specs"
create_profile "$test8_specs"
test8_spec_dir="$test8_specs/my-feature"
mkdir -p "$test8_spec_dir"

# use a repo with no changes since last commit
test8_repo=$(setup_git_repo)

output=$(run_verification_gate "$test8_spec_dir" "T-1" "$test8_repo" 2>&1)
exit_code=$?

assert_eq "$exit_code" "0" "no-diff gate exits 0"
assert_contains "$output" "No diff detected -- verification gate skipped." "prints skip message for no diff"

# ══════════════════════════════════════════════════════════════
echo ""
echo "=== Results ==="
echo "Passed: $PASS"
echo "Failed: $FAIL"
echo "Total:  $((PASS + FAIL))"

if [[ $FAIL -gt 0 ]]; then
    exit 1
fi
echo "All tests passed."
exit 0
