#!/usr/bin/env bash
# test-scanner-output.sh -- structural validation for spec-scanner output format
# Tests that a generated _project-profile.md conforms to the expected schema.
#
# Usage:
#   ./tests/test-scanner-output.sh [path-to-profile]
#
# If no path given, uses a built-in sample profile for format checks.
# For the self-scan test (test 5), run the scanner on this repo first,
# then pass the generated profile path.

set -euo pipefail

PASS=0
FAIL=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TMP_DIR=""

cleanup() {
    [[ -n "$TMP_DIR" && -d "$TMP_DIR" ]] && rm -rf "$TMP_DIR"
}
trap cleanup EXIT

TMP_DIR="$(mktemp -d)"

# ── helpers ──────────────────────────────────────────────────

pass() { PASS=$((PASS + 1)); echo "  PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1"; }

assert_contains() {
    local file="$1" pattern="$2" label="$3"
    if grep -qE "$pattern" "$file"; then
        pass "$label"
    else
        fail "$label -- pattern not found: $pattern"
    fi
}

assert_not_contains() {
    local file="$1" pattern="$2" label="$3"
    if grep -qEi "$pattern" "$file"; then
        fail "$label -- prohibited pattern found: $pattern"
    else
        pass "$label"
    fi
}

assert_section_exists() {
    local file="$1" section="$2"
    if grep -q "^## ${section}$" "$file"; then
        pass "Section exists: ## $section"
    else
        fail "Missing section: ## $section"
    fi
}

# ── generate sample profile for format tests ────────────────

SAMPLE_PROFILE="$TMP_DIR/sample-profile.md"
cat > "$SAMPLE_PROFILE" << 'PROFILE_EOF'
# Project Profile

> Auto-generated by spec-scanner. Last updated: 2026-04-01 14:30

## Stack

- Framework: Next.js 14 (App Router)
- Language: TypeScript 5.x
- Backend: API routes in app/api/
- Database: Prisma + PostgreSQL
- Styling: Tailwind CSS

## Patterns

### Route Registration [confidence: high]

New pages are created as `app/<path>/page.tsx` files. The file-based router picks them up automatically.

### Navigation [confidence: medium]

The main navigation is in `src/components/Sidebar.tsx:23-45`. New nav links are added as `<NavLink>` elements.

### API Endpoints [confidence: high]

API routes live in `app/api/<resource>/route.ts`. Each file exports named functions: `GET`, `POST`, `PUT`, `DELETE`.

### Database Models [confidence: low]

Low confidence pattern: Prisma schema assumed at `prisma/schema.prisma` based on framework detection. Verify with user if critical to the current task.

## Entity Registry

| Entity | Create | Read | Update | Delete | Notes |
|--------|--------|------|--------|--------|-------|
| User | yes | yes | yes | no | Missing soft-delete |
| Invoice | yes | yes | partial | no | Read-only after creation |
| Product | yes | yes | yes | yes | Full CRUD |

## Registration Points

- `app/` -- Create `<path>/page.tsx` for new pages
- `app/api/` -- Create `<resource>/route.ts` for new API endpoints
- `prisma/schema.prisma` -- Add new Prisma models
- `src/components/Sidebar.tsx:23` -- Add `<NavLink>` for new pages

## Regression Markers

(none)

## Manual Overrides

(user-editable -- preserved across rescans)
PROFILE_EOF

# allow user to pass a real profile path for tests 1-4
PROFILE="${1:-$SAMPLE_PROFILE}"

echo "============================================"
echo " Test Suite: spec-scanner output validation"
echo "============================================"
echo ""
echo "Profile under test: $PROFILE"
echo ""

# ── Test 1: All six required sections present ────────────────

echo "--- Test 1: Required sections ---"
assert_section_exists "$PROFILE" "Stack"
assert_section_exists "$PROFILE" "Patterns"
assert_section_exists "$PROFILE" "Entity Registry"
assert_section_exists "$PROFILE" "Registration Points"
assert_section_exists "$PROFILE" "Regression Markers"
assert_section_exists "$PROFILE" "Manual Overrides"
echo ""

# ── Test 2: Confidence labels on pattern entries ─────────────

echo "--- Test 2: Confidence labels ---"

# every ### heading under Patterns should have [confidence: high|medium|low]
pattern_headings=$(grep -c '^### ' "$PROFILE" || true)
confidence_labels=$(grep -c '\[confidence: \(high\|medium\|low\)\]' "$PROFILE" || true)

if [[ "$pattern_headings" -gt 0 && "$pattern_headings" -eq "$confidence_labels" ]]; then
    pass "All $pattern_headings pattern headings have confidence labels"
elif [[ "$pattern_headings" -eq 0 ]]; then
    fail "No pattern headings found (expected ### headings under ## Patterns)"
else
    fail "Confidence label mismatch: $pattern_headings headings but $confidence_labels labels"
fi

# verify only valid confidence values used
if grep -q '\[confidence: ' "$PROFILE"; then
    invalid=$(grep '\[confidence: ' "$PROFILE" | grep -cvE '\[confidence: (high|medium|low)\]' || true)
    if [[ "$invalid" -eq 0 ]]; then
        pass "All confidence labels use valid values (high/medium/low)"
    else
        fail "$invalid confidence labels have invalid values (not high/medium/low)"
    fi
else
    fail "No confidence labels found in profile"
fi
echo ""

# ── Test 3: Entity Registry table format ─────────────────────

echo "--- Test 3: Entity Registry table ---"

assert_contains "$PROFILE" \
    '^\| *Entity *\| *Create *\| *Read *\| *Update *\| *Delete *\| *Notes *\|' \
    "Entity Registry has correct header columns"

# check separator row
assert_contains "$PROFILE" \
    '^\|[-| ]+\|$' \
    "Entity Registry has separator row"

# check data rows use yes/no/partial
entity_data_lines=$(sed -n '/^## Entity Registry/,/^## /p' "$PROFILE" | grep -c '^|' || true)
if [[ "$entity_data_lines" -ge 3 ]]; then
    # at least header + separator + 1 data row
    pass "Entity Registry has data rows (found $((entity_data_lines - 2)) entity rows)"
else
    fail "Entity Registry has fewer than 1 data row ($entity_data_lines total table lines)"
fi

# verify CRUD cells use expected values
bad_crud=$(sed -n '/^## Entity Registry/,/^## /p' "$PROFILE" \
    | grep '^|' \
    | tail -n +3 \
    | awk -F'|' '{for(i=3;i<=6;i++) { gsub(/^ +| +$/,"",$i); if ($i != "yes" && $i != "no" && $i != "partial") print NR": field "i" = ["$i"]" }}' || true)
if [[ -z "$bad_crud" ]]; then
    pass "All CRUD cells use yes/no/partial"
else
    fail "Invalid CRUD values found: $bad_crud"
fi
echo ""

# ── Test 4: No credentials or secrets ────────────────────────

echo "--- Test 4: No credential leaks ---"
assert_not_contains "$PROFILE" '(password|secret|api.?key|token|bearer|aws_access|aws_secret)=' \
    "No credential assignments in profile"
assert_not_contains "$PROFILE" '\.env' \
    "No .env file references in profile"
assert_not_contains "$PROFILE" '(BEGIN (RSA |EC |DSA )?PRIVATE KEY|BEGIN CERTIFICATE)' \
    "No PEM content in profile"
echo ""

# ── Test 5: Self-scan expected output (spec-driven plugin repo) ──

echo "--- Test 5: Self-scan expected content (checklist) ---"
echo ""
echo "  This test validates that a scanner run on this repo detects key directories."
echo "  If testing with the sample profile, these checks will be skipped."
echo ""

# only run if the profile was generated from this repo (not the sample)
if [[ "$PROFILE" != "$SAMPLE_PROFILE" ]]; then
    # the scanner should detect these directories as containing meaningful artifacts
    assert_contains "$PROFILE" 'commands/' \
        "Profile mentions commands/ directory (slash command files)"
    assert_contains "$PROFILE" 'agents/' \
        "Profile mentions agents/ directory (agent definitions)"
    assert_contains "$PROFILE" 'scripts/' \
        "Profile mentions scripts/ directory (bash execution)"
    assert_contains "$PROFILE" 'plugin\.json' \
        "Profile mentions plugin.json (plugin manifest)"
    assert_contains "$PROFILE" 'templates/' \
        "Profile mentions templates/ directory"
else
    echo "  SKIP: Using sample profile. To run self-scan checks:"
    echo "    1. Run the spec-scanner agent on this repo"
    echo "    2. Pass the generated profile path:"
    echo "       ./tests/test-scanner-output.sh .claude/specs/_project-profile.md"
    echo ""
fi

echo ""
echo "  Expected self-scan profile content for this repo:"
echo "  ─────────────────────────────────────────────────"
echo "  ## Stack"
echo "    - Framework: Claude Code Plugin (spec-driven development)"
echo "    - Language: Bash (scripts), Markdown (agents/commands/skills)"
echo "    - Backend: n/a (plugin, not a web application)"
echo "    - Database: n/a"
echo "    - Styling: n/a"
echo ""
echo "  ## Patterns (expected detections)"
echo "    - Command Registration [confidence: high]"
echo "      commands/*.md files with YAML frontmatter (name, description, allowed-tools)"
echo "      18 command files detected"
echo "    - Agent Definitions [confidence: high]"
echo "      agents/*.md files with YAML frontmatter (name, description, model, tools)"
echo "      11 agent files detected"
echo "    - Script Execution [confidence: high]"
echo "      scripts/*.sh files for autonomous execution"
echo "    - Template Files [confidence: medium]"
echo "      templates/*.md files for document scaffolding"
echo ""
echo "  ## Entity Registry"
echo "    Not applicable -- this is a plugin, not a data-driven application."
echo "    Expected: empty table or a note explaining n/a."
echo ""
echo "  ## Registration Points"
echo "    - .claude-plugin/plugin.json -- Register new agents and commands"
echo "    - commands/ -- Create new slash command .md files"
echo "    - agents/ -- Create new agent .md files"
echo "    - CLAUDE.md -- Document new commands/agents in tables"
echo ""

# ── Test 6: 200-line split trigger ───────────────────────────

echo "--- Test 6: Profile split at 200 lines ---"

SPLIT_DIR="$TMP_DIR/split-test"
mkdir -p "$SPLIT_DIR"

# create a mock profile exceeding 200 lines
LARGE_PROFILE="$SPLIT_DIR/_project-profile.md"
{
    echo "# Project Profile"
    echo ""
    echo "> Auto-generated by spec-scanner. Last updated: 2026-04-01 15:00"
    echo ""
    echo "## Stack"
    echo "- Framework: Large Monolith App"
    echo "- Language: TypeScript"
    echo "- Backend: Express"
    echo "- Database: PostgreSQL"
    echo "- Styling: Tailwind"
    echo ""
    echo "## Patterns"
    echo ""

    # generate enough pattern entries to exceed 200 lines
    for domain in Auth Billing Products Orders Shipping Inventory Notifications Analytics; do
        lower=$(echo "$domain" | tr '[:upper:]' '[:lower:]')
        echo "### $domain Routes [confidence: high]"
        echo ""
        echo "Routes for the $lower domain are registered in \`src/$lower/routes.ts\`."
        echo "Each route handler is exported from \`src/$lower/handlers/\`."
        echo "New routes are added by creating a handler file and importing in routes.ts."
        echo "The route file exports a configureRoutes function that takes an Express Router."
        echo "Each handler follows the pattern: validate input, call service, return response."
        echo ""
        echo "### $domain Models [confidence: high]"
        echo ""
        echo "Models are defined in \`src/$lower/models/\`. Each model uses Sequelize."
        echo "New models need a migration in \`src/$lower/migrations/\`."
        echo "Models are registered in \`src/$lower/models/index.ts\` via dynamic import."
        echo "Each model exports a class extending BaseModel with tableName and schema."
        echo ""
        echo "### $domain Middleware [confidence: medium]"
        echo ""
        echo "Domain-specific middleware in \`src/$lower/middleware/\`."
        echo "Middleware handles auth checks, rate limiting, and request validation."
        echo ""
    done

    echo "## Entity Registry"
    echo ""
    echo "| Entity | Create | Read | Update | Delete | Notes |"
    echo "|--------|--------|------|--------|--------|-------|"
    for entity in User Account Invoice Payment Order Shipment Product Category Inventory Notification Alert Report Dashboard Webhook Token Session Role Permission AuditLog Setting Subscription Plan Coupon Address Warehouse Supplier Review Comment Tag Label Workflow Pipeline Event Metric; do
        echo "| $entity | yes | yes | yes | no | Standard CRUD |"
    done
    echo ""
    echo "## Registration Points"
    echo ""
    for domain in auth billing products orders shipping inventory notifications analytics; do
        echo "- \`src/${domain}/routes.ts:1\` -- Register ${domain} route handlers"
        echo "- \`src/${domain}/models/index.ts:1\` -- Export ${domain} models"
    done
    echo ""
    echo "## Regression Markers"
    echo ""
    echo "(none)"
    echo ""
    echo "## Manual Overrides"
    echo ""
    echo "(user-editable -- preserved across rescans)"
} > "$LARGE_PROFILE"

line_count=$(wc -l < "$LARGE_PROFILE")
if [[ "$line_count" -gt 200 ]]; then
    pass "Mock large profile has $line_count lines (> 200 threshold)"
else
    fail "Mock large profile only has $line_count lines (expected > 200)"
fi

# simulate what the scanner should produce when splitting
INDEX_FILE="$SPLIT_DIR/_profile-index.md"
cat > "$INDEX_FILE" << 'INDEX_EOF'
# Project Profile Index

> Auto-generated by spec-scanner. Last updated: 2026-04-01 15:00

| Domain | File | Summary |
|--------|------|---------|
| auth | _profile-auth.md | Authentication, sessions, roles, permissions |
| billing | _profile-billing.md | Payments, invoices, accounts |
| products | _profile-products.md | Products, categories, inventory |
| orders | _profile-orders.md | Orders, shipments, shipping |
INDEX_EOF

# create one domain profile to validate format
DOMAIN_PROFILE="$SPLIT_DIR/_profile-auth.md"
cat > "$DOMAIN_PROFILE" << 'DOMAIN_EOF'
# Project Profile: auth

> Auto-generated by spec-scanner. Last updated: 2026-04-01 15:00

## Stack

- Framework: Large Monolith App
- Language: TypeScript
- Backend: Express
- Database: PostgreSQL
- Styling: Tailwind

## Patterns

### Auth Routes [confidence: high]

Routes for the auth domain are registered in `src/auth/routes.ts`.

### Auth Models [confidence: high]

Models are defined in `src/auth/models/`. Each model uses Sequelize.

## Entity Registry

| Entity | Create | Read | Update | Delete | Notes |
|--------|--------|------|--------|--------|-------|
| User | yes | yes | yes | no | Standard CRUD |
| Session | yes | yes | no | yes | Create/read/delete only |
| Token | yes | yes | no | yes | Create/read/delete only |
| Role | yes | yes | yes | no | Standard CRUD |
| Permission | yes | yes | yes | no | Standard CRUD |

## Registration Points

- `src/auth/routes.ts:1` -- Register auth route handlers
- `src/auth/models/index.ts:1` -- Export auth models

## Regression Markers

(none)

## Manual Overrides

(user-editable -- preserved across rescans)
DOMAIN_EOF

# validate index format
assert_contains "$INDEX_FILE" '^\| *Domain *\| *File *\| *Summary *\|' \
    "Index file has correct table header"

index_entries=$(grep -c '^| [a-z]' "$INDEX_FILE" || true)
if [[ "$index_entries" -ge 2 ]]; then
    pass "Index lists $index_entries domain entries"
else
    fail "Index has fewer than 2 domain entries"
fi

# validate domain profile has all required sections
assert_section_exists "$DOMAIN_PROFILE" "Stack"
assert_section_exists "$DOMAIN_PROFILE" "Patterns"
assert_section_exists "$DOMAIN_PROFILE" "Entity Registry"
assert_section_exists "$DOMAIN_PROFILE" "Registration Points"
assert_section_exists "$DOMAIN_PROFILE" "Regression Markers"
assert_section_exists "$DOMAIN_PROFILE" "Manual Overrides"

# domain profile should have standalone readability (includes Stack)
assert_contains "$DOMAIN_PROFILE" '^- Framework:' \
    "Domain profile includes Stack section for standalone readability"

echo ""

# ── Summary ──────────────────────────────────────────────────

echo "============================================"
echo " Results: $PASS passed, $FAIL failed"
echo "============================================"

if [[ "$FAIL" -gt 0 ]]; then
    exit 1
fi
exit 0
